use kids_shop;

#ALTERING CURRENT TABLES FOR THE TASK
ALTER TABLE product ADD COLUMN AVERAGE_RATING DOUBLE NOT NULL DEFAULT 0;
ALTER TABLE product ADD COLUMN PRICE DOUBLE NOT NULL;
ALTER TABLE PRODUCT ADD FOREIGN KEY (category_id) REFERENCES category(ID);



#ADDING NEW TABLES
CREATE TABLE CUSTOMER(
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    SALARY INT NOT NULL
);

CREATE TABLE RATING(
    RATING_ID INT AUTO_INCREMENT PRIMARY KEY,
    RATING INT NOT NULL CHECK (RATING >=0 AND RATING <=5),
    CUSTOMER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    RATING_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(id)
);

CREATE TABLE INVOICE(
    INVOICE_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    EMPLOYEE_ID INT NOT NULL,
    INVOICE_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);

CREATE TABLE SALE(
    SALE_ID INT AUTO_INCREMENT PRIMARY KEY,
    INVOICE_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE INT NOT NULL,
    FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE(INVOICE_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES product(ID)
);


#ADDING ENTRIES
# Insert into customer table
INSERT INTO customer (name) VALUES ('John');
INSERT INTO customer (name) VALUES ('Alice');
INSERT INTO customer (name) VALUES ('Bob');
INSERT INTO customer (name) VALUES ('Emma');
INSERT INTO customer (name) VALUES ('Chris');

# Insert into employee table
INSERT INTO employee (employee_id, name, salary) VALUES (2, 'Alice', 1200);
INSERT INTO employee (employee_id, name, salary) VALUES (3, 'Bob', 1500);
INSERT INTO employee (employee_id, name, salary) VALUES (4, 'Emma', 1800);
INSERT INTO employee (employee_id, name, salary) VALUES (5, 'Chris', 2000);
INSERT INTO employee (employee_id, name, salary) VALUES (6, 'David', 1100);


INSERT INTO change_log (created_by, script_name, script_details) VALUES ('MUKIT MAHDIN', '001_A1_A2_ADD_TABLES.sql', 'COMPLETION OF THE FIRST TASK');