USE kids_shop;
DELIMITER //


#ADD RATINGS TO THE RATING TABLE
CREATE PROCEDURE ADD_RATING(
    IN P_PRODUCT_ID INT,
    IN P_RATING_VALUE INT,
    IN P_CUSTOMER_ID INT
)
BEGIN
    INSERT INTO rating (rating, customer_id, product_id)
    VALUES (P_RATING_VALUE, P_CUSTOMER_ID, P_PRODUCT_ID);
    UPDATE product
    SET average_rating = (SELECT AVG(rating) FROM rating WHERE product_id = P_PRODUCT_ID)
    WHERE id = P_PRODUCT_ID;
END //

DELIMITER ;

CALL ADD_RATING(1, 5, 1);
CALL ADD_RATING(1, 4, 1);
CALL ADD_RATING(2, 4, 2);
CALL ADD_RATING(3, 3, 3);
CALL ADD_RATING(4, 5, 4);
CALL ADD_RATING(5, 5, 5);
CALL ADD_RATING(6, 4, 1);


#GETTING THE AVERAGE RATING

DELIMITER //

CREATE PROCEDURE GET_AVERAGE_RATING(
    IN P_PRODUCT_ID INT,
    OUT P_AVERAGE_RATING DOUBLE
)
BEGIN
    DECLARE COUNTS INT;
    DECLARE SUM_OF_RATINGS INT;

    SELECT COUNT(*) INTO COUNTS
    FROM RATING
    WHERE PRODUCT_ID = P_PRODUCT_ID;

    SELECT SUM(RATING) INTO SUM_OF_RATINGS
    FROM RATING
    WHERE PRODUCT_ID = P_PRODUCT_ID;

    UPDATE PRODUCT
    SET AVERAGE_RATING = SUM_OF_RATINGS / COUNTS
    WHERE ID = P_PRODUCT_ID;

    SELECT AVERAGE_RATING INTO P_AVERAGE_RATING
    FROM PRODUCT
    WHERE ID = P_PRODUCT_ID;
END //

DELIMITER ;

CALL GET_AVERAGE_RATING(2, @AVERAGE_RATING);
SELECT @AVERAGE_RATING;

INSERT INTO change_log (created_by, script_name, script_details) VALUES ('MAHDIN MUKIT', '002_B1_AVG_RATING.sql', 'COMPLETION OF THE B1 TASK');