server:
  port: 9004
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: http://localhost:9003/customers
          predicates:
            - Path=/customers/**
        - id: PRODUCT-SERVICE
          uri: http://localhost:9001/products
          predicates:
            - Path=/products/**
        - id: EMPLOYEE-SERVICE
          uri: http://localhost:9002/employees
          predicates:
            - Path=/employees/**
        - id: ORDER-SERVICE
          uri: http://localhost:9006/orders
          predicates:
            - Path=/orders/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: localhost